#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Public values are checked before the template writes plain dotenv lines.
validate_settings() {
  python3 - "$@" <<'CHECK'
import ipaddress, re, sys
from urllib.parse import urlsplit
url, engine, tls, hostname, bind, port = sys.argv[1:]
if not re.fullmatch(r'https?://(?:[A-Za-z0-9.-]+|\[[0-9A-Fa-f:]+\])(?::[0-9]+)?/?', url):
    sys.exit('Use a plain public origin with no dotenv expansion or control syntax.')
u = urlsplit(url)
try:
    if u.port is not None and not 1 <= u.port <= 65535:
        raise ValueError()
except ValueError:
    sys.exit('Use an origin port from 1 to 65535.')
if u.username or u.password or u.query or u.fragment or u.path not in ('', '/') or not u.hostname:
    sys.exit('Use the public KyPost origin without credentials, query or path.')
if u.scheme != 'https' and not (u.scheme == 'http' and u.hostname in ('localhost', '127.0.0.1', '::1')):
    sys.exit('Use HTTPS, or loopback HTTP for the local test.')
for path in (engine, tls):
    if not re.fullmatch(r'/[A-Za-z0-9_./-]+', path):
        sys.exit('Use absolute engine/TLS paths containing letters, digits, slash, dot, underscore or hyphen.')
if len(hostname) > 253 or '.' not in hostname or any(not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?', label) for label in hostname.split('.')):
    sys.exit('Use the lowercase certificate DNS hostname, without a wildcard or trailing dot.')
try:
    if bind.startswith('[') and bind.endswith(']'):
        if ipaddress.IPv6Address(bind[1:-1]).scope_id is not None:
            raise ValueError()
    else:
        ipaddress.IPv4Address(bind)
except ValueError:
    sys.exit('Use a literal IPv4 publish address, or bracketed IPv6 address without a scope ID.')
if not re.fullmatch(r'[1-9][0-9]{0,4}', port) or int(port) > 65535:
    sys.exit('Use an explicit SMTP publish port from 1 to 65535.')
CHECK
}

validate_files() {
  [[ -f "$1" && ! -L "$1" && -x "$1" ]] || { warn 'Supply the regular nonsymlink qualified engine executable.'; return 1; }
  [[ -d "$2" && ! -L "$2" ]] || { warn 'Supply an existing regular TLS directory.'; return 1; }
  for setup_pem in fullchain.pem privkey.pem; do
    [[ -f "$2/$setup_pem" && ! -L "$2/$setup_pem" ]] || { warn "Supply regular nonsymlink $setup_pem in the TLS directory."; return 1; }
  done
  [[ $(stat -c %a "$2/privkey.pem") == 600 && $(stat -c %u "$2/privkey.pem") == 1000 ]] \
    || { warn 'The TLS key must be mode 0600 and owned by image UID 1000; arrange that on the host.'; return 1; }
  [[ $(sha256sum "$1" | cut -d ' ' -f 1) == 6ea4b951f15b91fd81d98957e4d4bad7a0cec6d6e1d66b011c765cc9a14e05db ]] \
    || { warn 'The executable hash differs from the qualified Maddy 0.9.5 binary.'; return 1; }
}

prepare_env() {
  [[ ! -L "$ENV_FILE" ]] || { warn 'Refusing a symlinked .env; select an owned regular file.'; return 1; }
  if [[ -e "$ENV_FILE" ]]; then
    [[ -f "$ENV_FILE" && -O "$ENV_FILE" && $(stat -c %a "$ENV_FILE") == 600 ]] \
      || { warn 'Use an owned regular .env with mode 0600 before rerunning.'; return 1; }
  else
    (umask 077; cp "$1" "$ENV_FILE")
  fi
}
require_confirmation() { confirm "$1" || { printf '%sStopped at your choice; retain existing settings and mail state.%s\n' "$RED" "$RESET" >&2; exit 1; }; }
compose_base() {
  SERVER_BASE_URL="$setup_url" KYPOST_BIND="$KYPOST_BIND" KYPOST_NATIVE_MAIL=true KYPOST_NATIVE_RECEIVING=false \
    docker compose --env-file "$ENV_FILE" -f "$setup_repo/docker-compose.yml" "$@"
}
compose_receiving() {
  SERVER_BASE_URL="$setup_url" KYPOST_BIND="$KYPOST_BIND" KYPOST_MADDY_BINARY="$KYPOST_MADDY_BINARY" KYPOST_RECEIVING_TLS_DIR="$KYPOST_RECEIVING_TLS_DIR" \
    KYPOST_RECEIVING_HOSTNAME="$KYPOST_RECEIVING_HOSTNAME" KYPOST_SMTP_BIND="$KYPOST_SMTP_BIND" KYPOST_SMTP_PORT="$KYPOST_SMTP_PORT" \
    docker compose --env-file "$ENV_FILE" -f "$setup_repo/docker-compose.yml" -f "$setup_repo/docker-compose.receiving.yml" "$@"
}

# BEGIN INTERACTIVE STAGES
# Tests load only the definitions above; browsers and deployment stay human-run.
[[ -t 0 ]] || { printf 'Run interactively: bash scripts/setup-mail.sh https://your-kypost-origin\n' >&2; exit 1; }
[[ $# == 1 ]] || { printf 'Usage: bash scripts/setup-mail.sh <public-KyPost-origin>\n' >&2; exit 1; }
[[ $(id -u) != 0 && $(uname -s):$(uname -m) == Linux:x86_64 ]] || { printf 'Run as the unprivileged Docker operator on qualified Linux x86_64.\n' >&2; exit 1; }
for setup_command in python3 docker sha256sum stat; do
  command -v "$setup_command" >/dev/null || { printf 'Install %s before setup.\n' "$setup_command" >&2; exit 1; }
done
docker compose version >/dev/null
setup_url=${1%/}
validate_settings "$setup_url" /placeholder /placeholder mail.example.com 127.0.0.1 2525
setup_repo=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
cd "$setup_repo"
case "$ENV_FILE" in /*) ;; *) ENV_FILE="$setup_repo/$ENV_FILE" ;; esac
validate_settings "$setup_url" "$ENV_FILE" /placeholder mail.example.com 127.0.0.1 2525
umask 077
TOTAL_STAGES=8
banner 'KyPost controlled domain test'

stage 'Secure base deployment'
warn 'Use a dedicated test deployment/domain. This does not migrate existing IMAP mail.'
warn 'Recreating base Compose pauses any existing receiver. Preserve state and prior DNS.'
say 'Arrange the existing TLS/proxy settings in .env; see docs/Reverse_Proxy_Networking.md.'
ask KYPOST_BIND 'HTTP publish address (choose for your proxy; no inherited default):'
validate_settings "$setup_url" /placeholder /placeholder mail.example.com "$KYPOST_BIND" 5866
require_confirmation 'Prepare native mode and rebuild this checkout for the dedicated test?'
prepare_env .env.example
write_env KYPOST_BIND "$KYPOST_BIND"
write_env SERVER_BASE_URL "$setup_url"
write_env KYPOST_NATIVE_MAIL true
write_env KYPOST_NATIVE_RECEIVING false
compose_base config -q
compose_base up --build -d
open_url "$setup_url"
say 'Confirm the HTTPS/proxy configuration and sign in as the administrator.'
say 'For a fresh server, follow README first-start credential retrieval; the wizard never captures passwords.'
require_confirmation 'Can you reach the intended secure KyPost deployment?'

stage 'KyIdentity, domain proof and a new native user'
open_url "$setup_url"
step 'Pair KyIdentity under Server → SSO; open Server → Mail domain.'
step 'Create the dedicated-domain challenge, publish its exact TXT name/value and verify it.'
step 'Keep TXT in place. Assign a new active test identity with an explicit primary address in that domain.'
step 'Confirm that identity can sign in and access its newly prepared native mailbox.'
require_confirmation 'Are domain proof and the new native test mailbox ready?'

stage 'Operator-owned outgoing relay'
open_url "$setup_url"
step 'Use Server → Mail domain to enter the provider implicit-TLS endpoint and SMTP credentials.'
step 'Complete sender/domain verification and provider DNS setup using the provider instructions.'
say 'AWS SES/Cloudflare requirements: docs/TURNKEY_MAIL_STACK_PLAN.md, Operator-owned relay test matrix.'
step 'Save the profile, then choose Check saved relay and confirm in the UI.'
warn 'Enter credentials only in the protected UI. TLS/AUTH success does not prove delivery.'
require_confirmation 'Did the saved-relay check succeed for the intended current provider profile?'

stage 'Receiver engine, TLS and publish inputs'
say 'Supply the qualified Maddy file separately; the wizard does not download it.'
say 'Release pin/provenance limits: docs/RECEIVING_GATEWAY_ASSESSMENT.md.'
say 'Supply fullchain.pem and privkey.pem readable by image UID 1000; key mode 0600.'
warn 'The receiver shares instance mail-storage authority. Keep host engine/TLS paths protected.'
say 'For external email choose a reachable address and port 25 explicitly; loopback/high ports are local-only.'
ask KYPOST_MADDY_BINARY 'Absolute qualified engine path:'
ask KYPOST_RECEIVING_TLS_DIR 'Absolute protected TLS directory:'
ask KYPOST_RECEIVING_HOSTNAME 'Lowercase certificate hostname:'
ask KYPOST_SMTP_BIND 'SMTP publish address (IPv4 or bracketed IPv6):'
ask KYPOST_SMTP_PORT 'SMTP publish port:'
validate_settings "$setup_url" "$KYPOST_MADDY_BINARY" "$KYPOST_RECEIVING_TLS_DIR" "$KYPOST_RECEIVING_HOSTNAME" "$KYPOST_SMTP_BIND" "$KYPOST_SMTP_PORT"
validate_files "$KYPOST_MADDY_BINARY" "$KYPOST_RECEIVING_TLS_DIR"
require_confirmation 'Save these five public receiving inputs in the protected .env?'
for setup_key in KYPOST_MADDY_BINARY KYPOST_RECEIVING_TLS_DIR KYPOST_RECEIVING_HOSTNAME KYPOST_SMTP_BIND KYPOST_SMTP_PORT; do
  write_env "$setup_key" "${!setup_key}"
done
compose_receiving config -q

stage 'Backups and rollback'
open_url "$setup_url"
step 'Open Server → Backup, configure sealed backups and check the deposit receipt and restore drill.'
step 'Keep an independent copy/destination, previous DNS/settings and a compatible KyPost binary.'
warn 'Native restores remain held; there is no supported hold release yet. Read docs/RESTORE.md.'
warn 'This is a controlled test profile. Do not change production MX or erase mail/receipts as rollback.'
require_confirmation 'Have you checked the backup result and recorded the test rollback route?'

stage 'Receiving spool initialization'
say 'Initialize exactly once after domain/account preparation, as kypost. Never repair by deleting the spool.'
if confirm 'Is this a NEW receiving spool that you explicitly want to initialize now?'; then
  compose_base exec --user kypost -e KYPOST_NATIVE_RECEIVING=true kypost-server kypost-server receiving init
else
  say 'Retaining the existing spool. Missing/held storage will refuse startup; do not bypass it.'
fi

stage 'Launch and check the controlled receiver'
require_confirmation 'Start the read-only engine/TLS receiving profile with the selected SMTP publish?'
compose_receiving up -d
setup_running=false
for ((setup_attempt=0; setup_attempt<30; setup_attempt++)); do
  setup_status=$(compose_receiving exec -T kypost-server supervisorctl -c /etc/supervisord.conf status receiver 2>/dev/null) || setup_status='not ready'
  if [[ $setup_status =~ ^receiver[[:space:]]+RUNNING[[:space:]] ]]; then setup_running=true; break; fi
  sleep 2
done
[[ $setup_running == true ]] || { warn 'Receiver not RUNNING. Inspect receiver.err.log and fix inputs/authority; retain state.'; exit 1; }
compose_receiving exec -T --user kypost kypost-server kypost-server receiving config \
  0.0.0.0:2525 "$KYPOST_RECEIVING_HOSTNAME" /opt/kypost/receiving/tls/fullchain.pem /opt/kypost/receiving/tls/privkey.pem >/dev/null
say 'Receiver started with fresh configuration admission. This does not prove public TLS or delivery.'

stage 'Bidirectional test and external readiness'
open_url "$setup_url"
step 'Check the public certificate chain/hostname and inbound port 25 from an independent client/network.'
step 'After those checks, arrange only the dedicated test-domain route; keep production MX unchanged.'
step 'Receive ordinary/PGP mail, attachments and controlled Bcc; inspect native mailboxes and raw MIME.'
step 'Reply through the operator relay; check outbox, Sent, provider logs and actual recipient receipt.'
warn 'An uncertain send requires provider evidence before retrying. Acceptance is not inbox placement.'
say 'Repeat backup after test mail; retain the receipt. Record observations without credentials.'
say 'Rollback: stop reception first, restore prior test DNS, retain/reconcile accepted state; no IMAP migration.'
# ponytail: human observes external reachability/delivery; automate only with a
# separately qualified probe that cannot confuse relay acceptance with receipt.
say 'Wizard steps prepared. External checks remain your responsibility; startup is not setup completion.'
